jobs:
  include:
    - stage: test discovery-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/discovery-service
    - stage: test user-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/user-service
      install:
        - oraclejdk8
    - stage: test task-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/task-service
      install:
        - oraclejdk8
    - stage: test test-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/test-service
    - stage: test task-executor-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/task-executor-service
    - stage: test result-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/result-service
    - stage: test gateway-service
      language: java
      jdk:
        - oraclejdk8
      before_install: cd $TRAVIS_BUILD_DIR/services/gateway-service